# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "99385542f8ef479b57c0e0cf24d438e5"
name = "variable-pricing"
application_url = "https://variable-pricing.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://variable-pricing.vercel.app/api/auth" ]
